osh_add_qt_project(DoorUnlockController QT_MODULES Sql)
target_compile_definitions(DoorUnlockController PRIVATE MAKE_SHARED_LIB)
target_link_libraries(DoorUnlockController PRIVATE Core)
find_library(WIRINGPI_LIBRARY wiringPi)
if(WIRINGPI_LIBRARY)
	target_link_libraries(DoorUnlockController PRIVATE ${WIRINGPI_LIBRARY})
endif()