add_subdirectory(onvifcore/OnvifDeviceLib)
add_subdirectory(onvifcore/OnvifDiscoveryLib)
add_subdirectory(onvifcore/OnvifEventLib)
add_subdirectory(OnvifAnalyticsLib)
add_subdirectory(OnvifDeviceIOLib)
add_subdirectory(OnvifDisplayLib)
add_subdirectory(OnvifImagingLib)
add_subdirectory(OnvifMediaLib)
add_subdirectory(OnvifPTZLib)
add_subdirectory(OnvifReceiverLib)
add_subdirectory(OnvifRecordingControlLib)
add_subdirectory(OnvifRecordingSearchLib)
add_subdirectory(OnvifReplayControlLib)
add_subdirectory(OnvifVideoAnalyticsDeviceLib)