#ifndef DEVICE_H
#define DEVICE_H

#define DEVICE_CONFIG_SERIAL_ID "device.serialId"

#define DEFAULT_DD_BROADCAST_INTERVAL 10000

#define DEFAULT_DD_ONLINE_CHECK_INTERVAL 10000

#define DEFAULT_DD_ONLINE_CHECK_TIMEOUT 30000

#endif // DEVICE_H
