#ifndef VALUE_QT_H
#define VALUE_QT_H

#include <QObject>

#include "sharedlib.h"

#define USES_VALUE_QT

#include "constants.h"
#include "value.h"


namespace value {
SHARED_LIB_EXPORT Q_NAMESPACE

    enum VALUE_TYPE {
        VALTYPE_UNKNOWN = ENUM_UNKNOWN,
        VALTYPE_BRIGHTNESS = VALUE_TYPE_BRIGHTNESS,
        VALTYPE_TEMP = VALUE_TYPE_TEMP,
        VALTYPE_STATIC_TEMP = VALUE_TYPE_STATIC_TEMP,
        VALTYPE_HUMIDITY = VALUE_TYPE_HUMIDITY,
        VALTYPE_MOTION = VALUE_TYPE_MOTION,
        VALTYPE_WATER_FLOW = VALUE_TYPE_WATER_FLOW,
        VALTYPE_WATER_LEVEL = VALUE_TYPE_WATER_LEVEL,
        VALTYPE_TIMESTAMP = VALUE_TYPE_TIMESTAMP,
        VALTYPE_ENERGY_CONSUMPTION = VALUE_TYPE_ENERGY_CONS,
        VALTYPE_ENERGY_CONSUMPTION_TIME = VALUE_TYPE_ENERGY_CONS_TIME,
        VALTYPE_SWITCH = VALUE_TYPE_SWITCH,

        VALTYPE_SHUTTER_CLOSE_STATE = VALUE_TYPE_SHUTTER_CLOSE_STATE,
        VALTYPE_SHUTTER_TILT_STATE = VALUE_TYPE_SHUTTER_TILT_STATE,
        VALTYPE_SHUTTER_MODE = VALUE_TYPE_SHUTTER_MODE,

        VALTYPE_MOTION_RADAR = VALUE_TYPE_MOTION_RADAR,
        VALTYPE_MOTION_PIR = VALUE_TYPE_MOTION_PIR,
        VALTYPE_REED_CONTACT = VALUE_TYPE_REED_CONTACT,

        VALTYPE_RELAY_LIGHT = VALUE_TYPE_RELAY_LIGHT,
        VALTYPE_RELAY_SHUTTER = VALUE_TYPE_RELAY_SHUTTER,
        VALTYPE_RELAY_TEMP_VALVE = VALUE_TYPE_RELAY_TEMP_VALVE,
        VALTYPE_RELAY_DOOR_OPEN = VALUE_TYPE_RELAY_DOOR_OPEN,

        VALTYPE_AUDIO = VALUE_TYPE_AUDIO,
        VALTYPE_AUDIO_VOLUME = VALUE_TYPE_AUDIO_VOLUME,
        VALTYPE_ALARM_SOUND = VALUE_TYPE_ALARM_SOUND,

        VALTYPE_HEAT_PUMP_DATA = VALUE_TYPE_HEAT_PUMP_DATA,

        VALTYPE_DOOR_OPENER = VALUE_TYPE_DOOR_OPENER,

        VALTYPE_VIRTUAL_ACTOR = VALUE_TYPE_VIRTUAL_ACTOR

    };

    Q_ENUM_NS(VALUE_TYPE)
}
#endif // VALUE_QT_H
