node {
   stage('Git checkout') {
      echo "$PWD"

      checkout scm
      sh 'git submodule update --init'
   }

   stage('Build') {
      dir('deploy/rpi') {
         sudo bash -c './deploy.sh CoreService'
      }
   }
}
