package com.osh.actor;

public enum ActorCmds {

    ACTOR_CMD_UNKNOWN,
    ACTOR_CMD_ON,
    ACTOR_CMD_OFF,
    ACTOR_CMD_UP,
    ACTOR_CMD_DOWN,
    ACTOR_CMD_START,
    ACTOR_CMD_STOP,
    ACTOR_CMD_PAUSE,
    ACTOR_CMD_SHUTTER_HALF_CLOSE,
    ACTOR_CMD_SHUTTER_HALF_OPEN,
    ACTOR_CMD_SHUTTER_FULL_OPEN,
    ACTOR_CMD_SHUTTER_TURN_OPEN,
    ACTOR_CMD_SHUTTER_TURN_CLOSE;
	
}
