package com.osh.wbb12;

public enum WBB12_Input_Registers {
        OUTSIDE_TEMP_1,
        OUTSIDE_TEMP_2,
        ERROR_CODE,
        WARNING_CODE,
        NO_ERROR,
        OPERATING_DISPLAY,

        HK1_ROOM_TARGET_TEMP,
        HK1_ROOM_TEMP,
        HK1_ROOM_HUMIDITY,
        HK1_FLOW_TARGET_TEMP,
        HK1_FLOW_TEMP,

        HK2_ROOM_TARGET_TEMP,
        HK2_ROOM_TEMP,
        HK2_ROOM_HUMIDITY,
        HK2_FLOW_TARGET_TEMP,
        HK2_FLOW_TEMP,

        HK3_ROOM_TARGET_TEMP,
        HK3_ROOM_TEMP,
        HK3_ROOM_HUMIDITY,
        HK3_FLOW_TARGET_TEMP,
        HK3_FLOW_TEMP,

        HK4_ROOM_TARGET_TEMP,
        HK4_ROOM_TEMP,
        HK4_ROOM_HUMIDITY,
        HK4_FLOW_TARGET_TEMP,
        HK4_FLOW_TEMP,

        WARM_WATER_TARGET_TEMP,
        WARM_WATER_TEMP,

        HEAT_PUMP_MODE,
        HEAT_PUMP_ERROR,
        HEAT_PUMP_CONSUMPTION,
        HEAT_PUMP_FLOW_TEMP,
        HEAT_PUMP_RETURN_FLOW_TEMP,

        HEAT_COIL_STATUS,
        HEAT_COIL_WORKING_HOURS,
        HEAT_COIL_SWITCH,
        HEAT_COIL_STATUS_COIL1,
        HEAT_COIL_STATUS_COIL2,
        HEAT_COIL_WORKING_HOURS_COIL1,
        HEAT_COIL_WORKING_HOURS_COIL2,

        ENERGY_TOTAL_TODAY,
        ENERGY_TOTAL_YESTERDAY,
        ENERGY_TOTAL_MONTH,
        ENERGY_TOTAL_YEAR,

        ENERGY_HEATING_TODAY,
        ENERGY_HEATING_YESTERDAY,
        ENERGY_HEATING_MONTH,
        ENERGY_HEATING_YEAR,

        ENERGY_WARM_WATER_TODAY,
        ENERGY_WARM_WATER_YESTERDAY,
        ENERGY_WARM_WATER_MONTH,
        ENERGY_WARM_WATER_YEAR,

        ENERGY_COOLING_TODAY,
        ENERGY_COOLING_YESTERDAY,
        ENERGY_COOLING_MONTH,
        ENERGY_COOLING_YEAR

}
