#!/usr/bin/env bash
set -euo pipefail

RPI_SYSROOT="$1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$SCRIPT_DIR/../.."
RPI_QTMQTT_BUILD_DIR="${RPI_QTMQTT_BUILD_DIR:-$ROOT_DIR/qtmqtt-build-rpi}"
RPI_TOOLCHAIN_FILE="$ROOT_DIR/deploy/rpi/xcompile_toolchain.cmake"
RPI_QT_ROOT="$RPI_SYSROOT/usr/local/qt6"
RPI_QT_HOST_ROOT="${RPI_QT_HOST_ROOT:-$HOME/qt-6.8.2}"
RPI_BUILD_JOBS="${RPI_BUILD_JOBS:-4}"
RPI_QT_SRC_DIR="${RPI_QT_SRC_DIR:-$ROOT_DIR/qt6}"
RPI_QT_MKSPECS_DIR="${RPI_QT_MKSPECS_DIR:-$RPI_QT_SRC_DIR/qtbase/mkspecs}"
RPI_QT_TARGET_MKSPEC="${RPI_QT_TARGET_MKSPEC:-linux-aarch64-gnu-g++}"
TARGET_QT_PREFIX_PATH="$RPI_QT_ROOT;$RPI_QT_HOST_ROOT"
RPI_QTMQTT_INSTALL="$RPI_QT_ROOT"

cmake -S "$ROOT_DIR/qtmqtt" -B "$RPI_QTMQTT_BUILD_DIR" \
    -G "Ninja" \
    -DCMAKE_TOOLCHAIN_FILE="$RPI_TOOLCHAIN_FILE" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH="$TARGET_QT_PREFIX_PATH" \
    -DQT_HOST_PATH="$RPI_QT_HOST_ROOT" \
    -DQt6HostInfo_DIR="$RPI_QT_HOST_ROOT/lib/cmake/Qt6HostInfo" \
    -DQT_MKSPECS_DIR="$RPI_QT_MKSPECS_DIR" \
    -DQT_QMAKE_TARGET_MKSPEC="$RPI_QT_TARGET_MKSPEC" \
    -DQT_GENERATE_SBOM=OFF \
    -DCMAKE_INSTALL_PREFIX="$RPI_QTMQTT_INSTALL" \
    -DQT_NO_PACKAGE_VERSION_CHECK=TRUE \
    -DQT_BUILD_EXAMPLES=OFF \
    -DQT_BUILD_TESTS=OFF \
    -DQT_BUILD_DOCS=OFF \
    "${TOOLCHAIN_ARGS[@]}"
cmake --build "$RPI_QTMQTT_BUILD_DIR" --parallel "$RPI_BUILD_JOBS"
sudo cmake --install "$RPI_QTMQTT_BUILD_DIR"
