#define WIFI_SSID_HOME21 "Home21"

#define DEVICE_ID_PREFIX "00"
#define SERVICE_ID_PREFIX "RELS-"
#define WIFI_SSID WIFI_SSID_HOME21

#define CONFIG_SHUTTER 0
#define CONFIG_POOL 1

#define TEMP_INTERVAL_MS 6000
#define TEMPS_VALUE_GROUP_ID "temps1"
#define TEMPS_VALUE_INDEX 0

#define HAS_TEMP_CONTROLLER_ONEWIRE true
#define RELAY_VALUE_GROUP_ID "allRelays9"
#define RELAY_VALUE_INDEX 2

#define ANALOG_INPUT_VALUE_GROUP_ID "pool"
#define ANALOG_INPUT_VALUE_INDEX 0
