#define PIN_SOUND_PIEZO 4
#define PIN_PIR_SENSOR 16
#define PIN_RCWL_SENSOR 17
#define PIN_BRIGHTNESS_SENSOR 34
#define PIN_KY002_SENSOR 32

#define PIN_FLOW_REED_SENSOR_1 27
#define PIN_FLOW_REED_SENSOR_2 12
#define PIN_FLOW_REED_SENSOR_3 33
#define PIN_FLOW_REED_SENSOR_4 14
