// COMMON PIN LAYOUT
#define PIN_SOUND_PIEZO 4
#define PIN_LED 26

// PIN LAYOUT FOR ROOM SENSOR
#define PIN_PIR_SENSOR 16
#define PIN_RCWL_SENSOR 17
#define PIN_BRIGHTNESS_SENSOR 34
#define PIN_KY002_SENSOR 32

// PIN LAYOUT FOR WATER SENSOR
#define PIN_FLOW_REED_SENSOR_1 27
#define PIN_FLOW_REED_SENSOR_2 12
#define PIN_FLOW_REED_SENSOR_3 33
#define PIN_FLOW_REED_SENSOR_4 14

// PIN LAYOUT FOR SHUTTER SENSOR
#define PIN_REED_SENSOR_1_CHECK 27
#define PIN_REED_SENSOR_1_VALUE 12
#define PIN_REED_SENSOR_2_CHECK 33
#define PIN_REED_SENSOR_2_VALUE 14
#define PIN_RELAY_UP 18
#define PIN_RELAY_DOWN 19
#define PIN_KY002_SENSOR 32

// AHT20
// SCL: 22
// SDA: 21
