#include "ESPConfigurations.h"

#define MQTT_CONTROLLER 0
#define DEVICE_CONTROLLER 1
#define TEMP_CONTROLLER 2
#define MOTION_CONTROLLER 3
#define BRIGHTNESS_CONTROLLER 4
#define SOUND_CONTROLLER 5
#define FLASH_CONTROLLER 6

#if WIFI_OTA_SUPPORT
  #define OTA_CONTROLLER 7
#endif
