#include "ESPConfigurations.h"

#define MQTT_CONTROLLER 0
#define DEVICE_CONTROLLER 1
#define FLASH_CONTROLLER 2
#define TEMP_CONTROLLER 3
#define MOTION_CONTROLLER 4
#define BRIGHTNESS_CONTROLLER 5
#define SOUND_CONTROLLER 6
#define WATER_CONTROLLER 7
#define OTA_CONTROLLER 8
